<?php

namespace App\Http\Controllers\Payroll;

use App\Actions\Payroll\SaveVacationPeriodAction;
use App\Http\Controllers\Controller;
use App\Http\Requests\Payroll\StoreVacationPeriodRequest;
use App\Http\Requests\Payroll\UpdateVacationPeriodRequest;
use App\Models\User;
use App\Models\VacationPeriod;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class VacationPeriodController extends Controller
{
    public function __construct(
        private readonly SaveVacationPeriodAction $saveVacationPeriodAction,
    ) {}

    /**
     * Create a vacation period for a collaborator (special cases: previous
     * history or a missing hire date). Calculated years are generated by the
     * system, so this covers the manual ones.
     */
    public function store(StoreVacationPeriodRequest $request, User $user): RedirectResponse
    {
        $this->saveVacationPeriodAction->execute($user, $request->validated(), $request->user());

        return back()->with('success', 'Periodo vacacional guardado.');
    }

    public function update(UpdateVacationPeriodRequest $request, VacationPeriod $period): RedirectResponse
    {
        $this->saveVacationPeriodAction->execute($period->user, $request->validated(), $request->user(), $period);

        return back()->with('success', 'Periodo vacacional actualizado.');
    }

    /**
     * Remove a period. The row is soft deleted so the automatic sync does not
     * generate it again.
     */
    public function destroy(Request $request, VacationPeriod $period): RedirectResponse
    {
        if (! $request->user()->can('payroll.vacations.manage')) {
            abort(403);
        }

        $period->delete();

        return back()->with('success', 'Periodo vacacional eliminado.');
    }
}
